# Generated by Django 6.0.6 on 2026-06-07 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='transcripts/')),
                ('filename', models.CharField(max_length=255)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('success', 'Sucesso'), ('error', 'Erro')], default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('engine_version', models.CharField(blank=True, max_length=20)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_documen_created_35997d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompilerError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('lexical', 'Léxica'), ('syntactic', 'Sintática'), ('semantic', 'Semântica')], max_length=20)),
                ('message', models.TextField()),
                ('line', models.PositiveIntegerField(default=0)),
                ('column', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='api.document')),
            ],
            options={
                'ordering': ['phase', 'line'],
            },
        ),
        migrations.CreateModel(
            name='CompilationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('tokens', models.JSONField(default=list)),
                ('syntax_tree', models.JSONField(blank=True, null=True)),
                ('semantic_analysis', models.JSONField(default=dict)),
                ('student_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.document')),
            ],
        ),
    ]
